### ISSUE TITLE
Tint.RGB.Convertible for Lab?

### ISSUE THREAD

**Issue by DaTrader** [tlux/tint#3]
Any chance of implementing Lab to RGB conversion?

Thanks

**Comment by m1dnight** [comment]
I've been trying to implement this, but it's actually not as easy as one would think. If anyone is interested I can start a PR to get to a working version, though.

Some reading that explains why it's rather difficult to achieve: 
https://stackoverflow.com/questions/7880264/convert-lab-color-to-rgb

Some code to get started: 
http://www.easyrgb.com/en/math.php

**Comment by DaTrader** [comment]
I already did it myself then and then realized these issues. 

Thanks anyway
