### ISSUE TITLE
Holy sh**

### ISSUE THREAD

**Issue by dsignr** [tlux/tint#4]
I spent my last 12 years working on a creative algorithm research project. I started with Ruby back then and used bare bones code from scratch to make my project work. Although, the outcome was a success, it was a commercial failure. 12 years later, here I am, trying to restart the project in Elixir but dealing with all the decimal conversion BS. And then I found your library after literally spending half my vacation time getting the old code to work. I found your work and probably saved the rest of my vacation now. Everything is just a simple function call. Your project helped me a LOT. It is super useful!
Thank you SO much!

**Comment by tlux** [comment]
Thank you very much!
